### ISSUE TITLE
Prepare for set-output deprecation

### ISSUE THREAD

**Issue by paambaati** [felipecrs/semantic-release-export-data#1]
`set-output` is being deprecated, see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The fix is to either manually write to `$GITHUB_OUTPUT` yourself, or better, use the `setOutput` method in `[@actions/core]`(https://www.npmjs.com/package/@actions/core).

**Comment by paambaati** [comment]
I cooked up a fix, but I would strongly urge you to include the `@actions/core` package instead to do this –

```diff
diff --git a/index.js b/index.js
index 2bb3e36..62d5ca9 100644
--- a/index.js
+++ b/index.js
@@ -1,5 +1,16 @@
+const { v4: uuidv4 } = require("uuid");
+const { EOL } = require("os");
+const { appendFileSync } = require("fs");
+
 function setOutput(name, value, stdout) {
-  stdout.write(`::set-output name=${name}::${value}\n`);
+  const filePath = process.env["GITHUB_OUTPUT"];
+  if (filePath) {
+    const delimiter = "ghadelimiter_" + uuidv4();
+    const output  = name + "<<" + delimiter + EOL + value + EOL + delimiter + EOL;
+    appendFileSync(filePath, output);
+  } else {
+    stdout.write(`::set-output name=${name}::${value}\n`);
+  }
 }
 
 function verifyConditions(_pluginConfig, { stdout }) {
```

I'm unsure of how to add dependencies to a semantic-release plugin, but I trust you can find this useful for a fix.

**Comment by paambaati** [comment]
References –

1. https://github.com/actions/toolkit/blob/b36e70495fbee083eb20f600eafa9091d832577d/packages/core/src/core.ts#L192-L200
2. https://github.com/actions/toolkit/blob/b36e70495fbee083eb20f600eafa9091d832577d/packages/core/src/file-command.ts#L11-L25
3. https://github.com/actions/toolkit/blob/b36e70495fbee083eb20f600eafa9091d832577d/packages/core/src/file-command.ts#L27-L47

**Comment by felipecrs** [comment]
Thanks a lot for the heads up, I will use the actions/core method instead.
