### ISSUE TITLE
Action returns true for existing release

### ISSUE THREAD

**Issue by paambaati** [felipecrs/semantic-release-export-data#3]
See https://github.com/paambaati/tfc-output-action/actions/runs/3350276723

semantic-release has generated 1.0.8, but that release is already published. Could this be a bug?

**Comment by paambaati** [comment]
I'm temporarily working around this with this – https://github.com/paambaati/tfc-output-action/commit/167a977d08519bd1acde07cc45f622c51893aeac

**Comment by felipecrs** [comment]
This doesn't make sense, but certainly has nothing to do with this plugin. Semantic Release detects the published versions according to the git tags but for some reason in your case it thinks the latest published version is v1.0.7 instead of v1.0.8.

**Comment by felipecrs** [comment]
I noticed one thing weird in your repo:

v1.0.8 tag is pointing to https://github.com/paambaati/tfc-output-action/commit/99d550c280618e8a134f9d3b58da62888d961f26 but it should point to https://github.com/paambaati/tfc-output-action/commit/e2a205f02f1a24550e2d73e333485c492c20e0bf

I would suggest you delete the tag and recreate it manually, then try to run the actions again.

**Comment by felipecrs** [comment]
I'll close this issue since there's nothing to be done in this plugin, but we can keep discussing it here.
