### ISSUE TITLE
Build job using wrong 'needs' name

### ISSUE THREAD

**Issue by Mashal-m** [felipecrs/semantic-release-export-data#4]
In the [Github Action Example](https://github.com/felipecrs/semantic-release-export-data#github-actions-example:~:text=GitHub%20Actions%20Example), the build job is using the wrong needs [name](https://github.com/felipecrs/semantic-release-export-data#github-actions-example:~:text=%3A%20ubuntu%2Dlatest-,needs%3A%20next%2Dversion,-if%3A%20needs). It should be **get-next-version**. 

**Here is the error ss**

<img width="1083" alt="Screenshot 2023-02-27 at 5 37 30 PM" src="https://user-images.githubusercontent.com/107556986/221565839-5fd3347f-2343-4d19-908c-ff5033224f92.png">

**Comment by felipecrs** [comment]
Thanks, fixed in https://github.com/felipecrs/semantic-release-export-data/commit/6c8be3b07a908cacb7925c578e8e860c6b4e8e74.
